import typescript from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import replace from "@rollup/plugin-replace";
import commonjs from "@rollup/plugin-commonjs";
import { env } from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
  input: "main.ts",
  output: {
    dir: ".",
    format: "cjs",
    exports: "default",
    banner,
  },
  external: ["obsidian", "fs", "os", "path"],
  plugins: [
    typescript(),
    nodeResolve({ browser: true }),
    replace({
      "process.env.NODE_ENV": JSON.stringify(env.NODE_ENV),
    }),
    commonjs(),
  ],
};
